### ISSUE TITLE
Autoplay Feature

### ISSUE THREAD

**Issue by svcino** [wootguy/voice_commands#5] opened 2020-05-29 12:32 UTC
`

**Comment by wootguy** [comment] 2020-05-29 20:58
I don't know what TFA-VOX did, but all the menus and sounds are customizable in this plugin. You or the server owner can add pain sounds by editing the .cfg files.

**Comment by wootguy** [comment] 2020-07-22 01:04
duplicate of #6 (?)

**Closed as completed by wootguy** 2020-07-22 01:04 UTC
